"""Verlaufsprotokoll einer Agenten-Sitzung — Beobachtungshilfe, kein Pipeline-Teil.

**Wozu.** Ein Migrationslauf, den ein Agent fuehrt, ist nur dann eine
Vorfuehrung, wenn sich hinterher nachvollziehen laesst, WAS passiert ist:
wer was gesagt hat, welche Kommandos liefen, wo eine Entscheidung fiel.
Die Gate-Ledger und die Entscheid-Snapshots halten das Ergebnis fest —
sie halten aber nicht fest, wie der Operator dorthin kam, was er
verworfen hat und wo er nachgefragt hat.

Claude Code schreibt ohnehin ein vollstaendiges Transkript je Sitzung
(``~/.claude/projects/<projekt>/<sitzung>.jsonl``, eine JSON-Zeile je
Ereignis). Dieses Werkzeug macht daraus ein lesbares Protokoll. Es
erzeugt nichts Neues und bewertet nichts — es stellt dar, was in der
Datei steht.

**Was es NICHT ist.** Kein Bestandteil der Migrations-Pipeline. Es liest
ein Herstellerformat (Claude Code) und ist damit an ein Werkzeug
gebunden, nicht an die Fachlichkeit. Es steht in ``werkzeuge/`` und
nicht in ``src/``, damit diese Grenze sichtbar bleibt (Beschluss
2026-08-28; die allgemeine Trennlinie zwischen versioniertem
Repo-Bestandteil und Beispielandockung ist ein offener Punkt, siehe
``dev-docs/offene-punkte.md``).

**Drei Dinge, die es sorgfaeltig macht.**

*Es trennt die Sprecher.* Im Transkript liegen menschliche Nachrichten,
Werkzeugergebnisse und System-Einblendungen im selben Kanal. Wer das
vermischt, legt dem Menschen Saetze in den Mund, die die Maschine
geschrieben hat. Unterschieden wird ueber ``isMeta``, ueber die
Blockarten und ueber die Einblendungsmarken.

*Es redigiert.* Ein Transkript kann Schluesselpfade und
Schluesselmaterial enthalten. Das Protokoll ist zum Herumzeigen gedacht,
also werden solche Stellen ersetzt. Die Redaktion ist bewusst grob: Ein
zu viel geschwaerzter Pfad ist harmlos, ein durchgerutschter Schluessel
nicht.

*Es liest stroemend.* Transkripte werden gross (achtzig Megabyte sind
normal). Die Datei wird zeilenweise gelesen und nie ganz in den Speicher
geholt.

Aufruf::

    python werkzeuge/verlaufsprotokoll.py --neueste --out verlauf.md
    python werkzeuge/verlaufsprotokoll.py --sitzung <uuid> --mit-denken
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional

#: Wo Claude Code seine Transkripte ablegt. Der Projektname entsteht aus
#: dem Arbeitsverzeichnis, indem Schraegstriche zu Bindestrichen werden.
TRANSKRIPTE = Path.home() / ".claude" / "projects"

#: Stellen, die im Protokoll nicht auftauchen duerfen. Bewusst grob —
#: ein zu viel geschwaerzter Pfad ist harmlos, ein durchgerutschter
#: Schluessel nicht.
#: Die Reihenfolge ist wesentlich: Das SPEZIFISCHERE Muster kommt
#: zuerst, sonst schwaerzt das allgemeinere einen Teil des Treffers und
#: das spaetere Muster laesst einen Rest stehen ("[redigiert] redigiert]").
REDAKTION = [
    (re.compile(r"(--freigabe-schluessel[= ])\S+"), r"\1[redigiert]"),
    (re.compile(r"[^\s\"']*\.secrets/[^\s\"']*"), "[Schluesselpfad redigiert]"),
    (re.compile(r"\b[A-Za-z0-9_-]{0,20}(?:api[_-]?key|token|secret|passwo?rt)"
                r"[\"'\s:=]+\S+", re.I), "[Geheimnis redigiert]"),
]

#: Kommandos, die eine Entscheidung festschreiben. Sie werden im
#: Protokoll hervorgehoben, weil an ihnen der Lauf haengt.
ENTSCHEIDUNGSSPUREN = (
    "gate_entscheid",
    "ontologie.entscheide",
)

#: Marken, an denen eine Nachricht als System-Einblendung erkennbar ist
#: und NICHT als Aeusserung des Menschen gilt. Die Liste ist an einem
#: echten Transkript gewachsen: Ohne sie wurden 614 statt rund 30
#: Beitraege dem Menschen zugeschrieben — Abbruchmarken, die
#: Kompaktierungs-Einblendung und Konsolenausgaben landeten in seinem
#: Mund. Wer hier etwas vergisst, faelscht das Protokoll.
EINBLENDUNGEN = (
    "<system-reminder>", "<local-command-", "<command-name>",
    "[SYSTEM NOTIFICATION",
    "[Request interrupted",
    "This session is being continued from a previous conversation",
    "Caveat: The messages below were generated by the user",
)

#: Der Mensch kann in der Sitzung selbst ein Kommando fahren (Praefix
#: ``!``). Das gehoert ins Protokoll — aber als Konsolenvorgang, nicht
#: als Aeusserung.
KONSOLE = ("<bash-input>", "<bash-stdout>", "<bash-stderr>")
_KONSOLE_KOMMANDO = re.compile(r"<bash-input>(.*?)</bash-input>", re.S)


def redigiere(text: str) -> str:
    for muster, ersatz in REDAKTION:
        text = muster.sub(ersatz, text)
    return text


def _projektverzeichnis(repo: Path) -> Path:
    """Das Transkriptverzeichnis zu einem Arbeitsverzeichnis."""
    name = str(repo.resolve()).replace("/", "-")
    return TRANSKRIPTE / name


def _sitzungsdatei(repo: Path, sitzung: Optional[str],
                   neueste: bool) -> Path:
    verzeichnis = _projektverzeichnis(repo)
    if sitzung:
        kandidat = Path(sitzung)
        if kandidat.is_file():
            return kandidat
        kandidat = verzeichnis / f"{sitzung}.jsonl"
        if kandidat.is_file():
            return kandidat
        raise SystemExit(f"Sitzung nicht gefunden: {sitzung} (gesucht in {verzeichnis})")
    if not verzeichnis.is_dir():
        raise SystemExit(f"Kein Transkriptverzeichnis: {verzeichnis}")
    dateien = sorted(verzeichnis.glob("*.jsonl"), key=lambda p: p.stat().st_mtime)
    if not dateien:
        raise SystemExit(f"Keine Transkripte in {verzeichnis}")
    if not neueste:
        raise SystemExit(
            "Mehrere Sitzungen vorhanden — mit --sitzung <uuid> waehlen oder "
            "--neueste nehmen. Vorhanden (neueste zuletzt):\n  "
            + "\n  ".join(p.stem for p in dateien[-10:])
        )
    return dateien[-1]


def _zeilen(pfad: Path) -> Iterator[Dict[str, Any]]:
    """Das Transkript stroemend lesen; kaputte Zeilen ueberspringen."""
    with pfad.open(encoding="utf-8") as datei:
        for rohzeile in datei:
            rohzeile = rohzeile.strip()
            if not rohzeile:
                continue
            try:
                yield json.loads(rohzeile)
            except ValueError:
                continue


def _zeit(eintrag: Dict[str, Any]) -> Optional[dt.datetime]:
    roh = eintrag.get("timestamp")
    if not roh:
        return None
    try:
        return dt.datetime.fromisoformat(str(roh).replace("Z", "+00:00"))
    except ValueError:
        return None


def _ist_einblendung(text: str) -> bool:
    anfang = text.lstrip()[:200]
    return any(marke in anfang for marke in EINBLENDUNGEN)


def _werkzeugzeile(block: Dict[str, Any]) -> str:
    """Einen Werkzeugaufruf auf eine Zeile bringen — Name plus Kern."""
    name = block.get("name", "?")
    eingabe = block.get("input") or {}
    if not isinstance(eingabe, dict):
        return f"{name}"
    for schluessel in ("command", "file_path", "pattern", "prompt",
                       "skill", "url", "description"):
        wert = eingabe.get(schluessel)
        if isinstance(wert, str) and wert.strip():
            kurz = " ".join(wert.split())
            if len(kurz) > 220:
                kurz = kurz[:217] + "..."
            return f"{name}: {kurz}"
    return name


def _ist_entscheidung(zeile: str) -> bool:
    return any(spur in zeile for spur in ENTSCHEIDUNGSSPUREN)


def sammle(pfad: Path, *, mit_denken: bool) -> Dict[str, Any]:
    """Das Transkript in eine Folge von Protokolleintraegen ueberfuehren."""
    eintraege: List[Dict[str, Any]] = []
    modelle: set = set()
    branches: set = set()
    erste = letzte = None

    for roh in _zeilen(pfad):
        art = roh.get("type")
        if art not in ("user", "assistant"):
            continue
        zeit = _zeit(roh)
        if zeit is not None:
            erste = erste or zeit
            letzte = zeit
        if roh.get("gitBranch"):
            branches.add(roh["gitBranch"])
        nachricht = roh.get("message")
        if not isinstance(nachricht, dict):
            continue

        if art == "user":
            if roh.get("isMeta"):
                continue
            inhalt = nachricht.get("content")
            texte = []
            if isinstance(inhalt, str):
                texte = [inhalt]
            elif isinstance(inhalt, list):
                # Werkzeugergebnisse sind KEINE Aeusserung des Menschen.
                texte = [b.get("text", "") for b in inhalt
                         if isinstance(b, dict) and b.get("type") == "text"]
            for text in texte:
                if not text.strip() or _ist_einblendung(text):
                    continue
                if any(marke in text[:200] for marke in KONSOLE):
                    treffer = _KONSOLE_KOMMANDO.search(text)
                    kommando = " ".join(treffer.group(1).split()) if treffer else ""
                    if kommando:
                        eintraege.append({"art": "konsole", "zeit": zeit,
                                          "text": kommando})
                    continue
                eintraege.append({"art": "mensch", "zeit": zeit,
                                  "text": text.strip()})
            continue

        modell = nachricht.get("model")
        if modell:
            modelle.add(modell)
        inhalt = nachricht.get("content")
        if not isinstance(inhalt, list):
            continue
        for block in inhalt:
            if not isinstance(block, dict):
                continue
            typ = block.get("type")
            if typ == "text" and block.get("text", "").strip():
                eintraege.append({"art": "operator", "zeit": zeit,
                                  "text": block["text"].strip()})
            elif typ == "thinking" and mit_denken:
                denken = block.get("thinking") or block.get("text") or ""
                if denken.strip():
                    eintraege.append({"art": "denken", "zeit": zeit,
                                      "text": denken.strip()})
            elif typ == "tool_use":
                zeile = _werkzeugzeile(block)
                eintraege.append({
                    "art": "entscheidung" if _ist_entscheidung(zeile) else "werkzeug",
                    "zeit": zeit, "text": zeile,
                })

    return {
        "datei": pfad,
        "eintraege": eintraege,
        "modelle": sorted(modelle),
        "branches": sorted(branches),
        "von": erste,
        "bis": letzte,
    }


_UEBERSCHRIFT = {
    "mensch": "Mensch",
    "operator": "Operator",
    "denken": "Operator (Ueberlegung)",
    "konsole": "Mensch an der Konsole",
    "werkzeug": "Werkzeug",
    "entscheidung": "Entscheid",
}


def als_markdown(lauf: Dict[str, Any]) -> str:
    aus: List[str] = []
    eintraege = lauf["eintraege"]
    zaehler: Dict[str, int] = {}
    for e in eintraege:
        zaehler[e["art"]] = zaehler.get(e["art"], 0) + 1

    aus.append("# Verlaufsprotokoll")
    aus.append("")
    aus.append(f"Sitzung: `{lauf['datei'].stem}`")
    if lauf["von"] and lauf["bis"]:
        aus.append(f"Zeitraum: {lauf['von']:%d.%m.%Y %H:%M} bis "
                   f"{lauf['bis']:%d.%m.%Y %H:%M} (UTC)")
    if lauf["branches"]:
        aus.append(f"Branch: {', '.join(lauf['branches'])}")
    if lauf["modelle"]:
        aus.append(f"Modell: {', '.join(lauf['modelle'])}")
    aus.append("")
    aus.append("| Art | Anzahl |")
    aus.append("|---|---:|")
    for art in ("mensch", "konsole", "operator", "werkzeug",
                "entscheidung", "denken"):
        if zaehler.get(art):
            aus.append(f"| {_UEBERSCHRIFT.get(art, art.capitalize())} "
                       f"| {zaehler[art]} |")
    aus.append("")
    aus.append("Erzeugt aus dem Sitzungstranskript. Werkzeugaufrufe stehen "
               "verkuerzt; Schluesselpfade sind redigiert. Entscheidungen "
               "sind hervorgehoben — sie schreiben den Lauf fest.")
    aus.append("")
    aus.append("---")
    aus.append("")

    letzte_art = None
    for e in eintraege:
        zeitmarke = f"{e['zeit']:%H:%M:%S}" if e["zeit"] else "--:--:--"
        text = redigiere(e["text"])
        if e["art"] in ("mensch", "operator", "denken"):
            aus.append(f"## {_UEBERSCHRIFT[e['art']]} — {zeitmarke}")
            aus.append("")
            aus.append(text)
            aus.append("")
        elif e["art"] == "konsole":
            aus.append(f"- `{zeitmarke}` **Mensch an der Konsole:** `{text}`")
        elif e["art"] == "entscheidung":
            aus.append(f"> **ENTSCHEID {zeitmarke}** — `{text}`")
            aus.append("")
        else:
            if letzte_art != "werkzeug":
                aus.append("")
            aus.append(f"- `{zeitmarke}` {text}")
        letzte_art = e["art"]

    aus.append("")
    return "\n".join(aus)


def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(
        description="Verlaufsprotokoll einer Agenten-Sitzung erzeugen.")
    p.add_argument("--sitzung", default=None,
                   help="Sitzungs-UUID oder Pfad zum Transkript")
    p.add_argument("--neueste", action="store_true",
                   help="die zuletzt geaenderte Sitzung des Projekts nehmen")
    p.add_argument("--repo", default=".",
                   help="Arbeitsverzeichnis, aus dem der Projektname folgt")
    p.add_argument("--out", default=None,
                   help="Zieldatei (Vorgabe: Standardausgabe)")
    p.add_argument("--mit-denken", action="store_true",
                   help="auch die Ueberlegungen des Operators aufnehmen")
    args = p.parse_args(argv)

    pfad = _sitzungsdatei(Path(args.repo), args.sitzung, args.neueste)
    lauf = sammle(pfad, mit_denken=args.mit_denken)
    if not lauf["eintraege"]:
        print(f"Transkript ohne verwertbare Eintraege: {pfad}", file=sys.stderr)
        return 1
    text = als_markdown(lauf)

    if args.out:
        ziel = Path(args.out)
        ziel.parent.mkdir(parents=True, exist_ok=True)
        ziel.write_text(text, encoding="utf-8")
        zahl = len(lauf["eintraege"])
        print(f"{ziel}: {zahl} Eintraege aus {pfad.name}")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
